### ISSUE TITLE
tmtpro flag only adds tag to lysines, not n-term.

### ISSUE THREAD

**Issue by ChrisMcGann** [wilhelm-lab/oktoberfest#123]
Hello,
Using the tmtpro flag in a config file only adds the tag to lysine. Attaching config file and input .csv. Thanks!

[prosit_input_minimal.zip](https://github.com/wilhelm-lab/oktoberfest/files/12580150/prosit_input_minimal.zip)

**Comment by picciama** [comment]
Thanks for pointing this out. I was able to reproduce this and know the reason for it. It will be fixed as part of the new API release.

**Comment by ChrisMcGann** [comment]
Awesome, glad to hear it.
