### ISSUE TITLE
minimalistic config files for all workflows

### ISSUE THREAD

**Issue by tobiasko** [wilhelm-lab/oktoberfest#128]
**Is your feature request related to a problem? Please describe.**

The current `/oktoberfest/example_config.json` needs to be heavily modified when wanting to run a different workflow.

**Describe the solution you would like**

I think it would be useful to provide example config files for all three workflows:

1. CE Calibration
2. SpectralLibraryGeneration
3. Rescoring

In addition one might think about incl. some minimalistic input  files and expected results. This would also allow implementing a unit test for all three workflows.

For 2. this could be a very small fasta file for instance:

```
>sp|ADD000|iRTKit iRT-Kit_WR_fusion
LGGNEQVTRYILAGVENSKGTFIIDPGGVIRGTFIIDPAAVIRGAGSSEPVTGLDAKTPVISGGPYEYRVEATFGVDESNAKTPVITGAPYEYRDGLDAASYYAPVRADVTPADFSEWSKLFLQFGAQGSPFLK
```
This protein would be digested into the iRT11 peptide set, using trypsin. All of these peptides have known HCD fragmentation patterns, RTs and inverse mobilities.

**Additional context**

**Comment by picciama** [comment]
We already have minimal config files for all three workflows in our documentation: https://oktoberfest.readthedocs.io/en/latest/jobs.html

Concerning your second point, yes most definitely a good idea. I will add individual tutorial notebooks using the new API once it is released.

**Comment by tobiasko** [comment]
Hi @picciama,

it is good to have those files in the docu, but I would also include them in the package, so they get installed on the local system of the user...

**Comment by picciama** [comment]
Valid point, I will include this in the next release.

**Comment by tobiasko** [comment]
👍
