### ISSUE TITLE
Does Oktoberfest already support Prosit_2023_intensity_TOF?

### ISSUE THREAD

**Issue by tobiasko** [wilhelm-lab/oktoberfest#136]
**Question**

Reading the [docu](https://github.com/wilhelm-lab/oktoberfest#supported-models) on GitHub I was wondering: Are latest Koina models already supported, especially the `Prosit_2023_intensity_TOF`? And do I understand this sentence:

"The model architecture remained unchanged."

The CE is still a model parameter?

**Comment by picciama** [comment]
This is related to #115 . I can start working on this at the end of the month. But yes, theoretically, it should work with relatively little change. However, there is a bit more connected to this which may require changes in spectrum-io and spectrum-fundamentals.

**Comment by tobiasko** [comment]
Yes and no. I think supporting the tims data format (tdf) directly would be cool, because it would avoid the .mzML conversion step. For me the question is more about the model usage. FragPipe for instance internally generates mzML files when you run a LFQ-MBR workflow. So could I CEcalibrate or rescore those search results with the Prosit_2023_intensity_TOF model? The data is available [here](http://fgcz-ms.uzh.ch/public/PXD028735/ddaPASEF/)

**Comment by WassimG** [comment]
It is not fully supported yet because CE calibration for TOF is different. And we need TimsR package to convert the .d folder to mzML. We are working on the integration, but it is not supported yet. I will let you know when it is fully integrated.

**Comment by tobiasko** [comment]
btw: Did anyone take a pciture of the oktoberfest dev team during Oktoberfest in Munich? Twitter?

**Comment by tobiasko** [comment]
> It is not fully supported yet because CE calibration for TOF is different. And we need TimsR package to convert the .d folder to mzML. We are working on the integration, but it is not supported yet. I will let you know when it is fully integrated.

@WassimG Do you really mean TimsR? Wouldn't [AlphaTims](https://github.com/MannLabs/alphatims) be the more obvious choice? Would you still convert to mzML if you could directly read the scan data from the .d folder?

**Comment by picciama** [comment]
@tobiasko @WassimG some good and bad news here: @adamscharlotte has implemented a solution with AlphaTims but I needed to copy parts of the MasterSpectrum code into spectrum-io because the [mgf_filter](https://github.com/kusterlab/MasterSpectrum) repository is not a PyPI package, which means we cannot depend on it. 

Charlotte went through her code with me so I can start merging this now, it still needs a bit of optimization, refactoring and debugging but I am hopeful that we're getting this integrated next week.
