### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: when running Spectral library generation

### ISSUE THREAD

**Issue by RicZenChioz** [wilhelm-lab/oktoberfest#147]
**Describe the bug**

When I ran the spectral library generation job through json input file i got this error FileNotFoundError: [Errno 2] No such file or directory: 'C:\\dataAnalysis\\Oktoberfest_test\\output_SpectralLibraryGenerator\\prosit_input.csv\\prosit_input.csv' 

**my json input file:**

```
{
    "type": "SpectralLibraryGeneration",
    "tag": "",
    "output": "C:/dataAnalysis/Oktoberfest_test/output_SpectralLibraryGenerator",
    "inputs": {
        "search_results": "C:/dataAnalysis/Oktoberfest_test/combined/txt/msms.txt",
        "search_results_type": "Maxquant",
        "library_input": "C:/dataAnalysis/Oktoberfest_test/HUMAN_uniprot_072022.fasta",
        "library_input_type": "fasta"
    },
    "models": {
        "intensity": "Prosit_2020_intensity_HCD",
        "irt": "Prosit_2019_irt"
    },
    "outputFormat": "spectronaut",
    "prediction_server": "koina.proteomicsdb.org:443",
    "numThreads": 12,
    "ssl": true,
    "fastaDigestOptions": {
        "fragmentation": "HCD",
        "digestion": "full",
        "missedCleavages": 2,
        "minLength": 7,
        "maxLength": 60,
        "enzyme": "trypsin",
        "specialAas": "KR",
        "db": "concat"
    }
}
```

**System information:**

-   OS: Windows 10
-   Language Version: Python 3.9
-   Virtual environment:  Conda

**Comment by picciama** [comment]
Oktoberfest performs an in-silico digest when you provided a fasta file and stores the peptide list in a file called prosit_input.csv which should reside in the specified output folder. In your case, this should be "C:\dataAnalysis\Oktoberfest_test\output_SpectralLibraryGenerator\prosit_input.csv". But I see the filename is duplicated at the end for some reason. I will come back to you once I find the reason this happens. 

Meanwhile, can you verify the file is indeed present in your output folder?

**Comment by RicZenChioz** [comment]
No the file is not present. I have tried two different scenarios. 
With the `"output": "C:/dataAnalysis/Oktoberfest_test/output_SpectralLibraryGenerator" ` set in the json file.

1. I run the software with only the Oktoberfest_test folder created (`C:/dataAnalysis/Oktoberfest_test/`).
2. I run te software with the output folder created (`C:/dataAnalysis/Oktoberfest_test/output_SpectralLibraryGenerator`).

In the case 1 the `output_SpectralLibraryGenerator` folder is not created and consequently no csv file is generated.
In the case 2, although I provide the folder, no csv file is returned.
