### ISSUE TITLE
--version

### ISSUE THREAD

**Issue by tobiasko** [wilhelm-lab/oktoberfest#228]
**Is your feature request related to a problem? Please describe.**

quick check if oktoberfest installation works/which version is executed

**Describe the solution you would like**

`--version` argument

**Additional context**

```
python -m oktoberfest --version
usage: __main__.py [-h] [--config_path C]
__main__.py: error: unrecognized arguments: --version
WARNING:root:WARNING: Temp mmap arrays were written to /tmp/temp_mmap_eln9f7kq. Cleanup of this folder is OS dependant, and might need to be triggered manually! Current space: 38,895,878,144
```
Would also be good if oktoberfest would print available parameters when being executed without any.

**Comment by picciama** [comment]
added it directly to the release/0.7.0 branch.
