### ISSUE TITLE
grpc._channel._InactiveRpcError: failed to connect to all addresses

### ISSUE THREAD

**Issue by qussai96** [wilhelm-lab/oktoberfest#56]
Hi everyone,

I have been trying to run Oktoberfest for rescoring on my machine. but I am having problems connecting to the server (the grpc client was unable to connect to the Linux ml server). I am using this ip address "10.152.135.57:8500" in my config file, and here is the error message: 

```
  File "/home/students/q.abbas/anaconda3/envs/okt/lib/python3.10/site-packages/prosit_grpc/predictPROSIT.py", line 60, in check_model_availability
    result = stub.GetModelStatus(request, 25)  # 5 secs timeout
  File "/home/students/q.abbas/anaconda3/envs/okt/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/students/q.abbas/anaconda3/envs/okt/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:10.152.135.57:8500: tcp handshaker shutdown"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:10.152.135.57:8500: tcp handshaker shutdown {created_time:"2023-03-17T11:53:25.576904432+01:00", grpc_status:14}"
```

Do you know what might cause this error? Am I using the wrong IP address?

Thanks,
Qussai

**Comment by picciama** [comment]
@qussai96 did you find out why this is? It is maybe due to a firewall issue on your side that prevents you from accessing the server?
@WassimG how should be best handle this for future users? I.e. can we come up with a better error handling here? Is this going to be solved once we switch to Triton?

**Comment by qussai96** [comment]
Hi,
Yes, I believe it is a firewall issue. I ran Oktoberfest on Linux-ml and on my office pc (which has access to Linux-ml) and everything worked just fine without any errors.
The bugs and the network connection errors occur only when running Oktoberfest on my machine (Although I am using the VPN certificate).

**Comment by picciama** [comment]
closing as it is a network issue on your side
