### ISSUE TITLE
Cannot connect to  standard Tritonserver using  grpc

### ISSUE THREAD

**Issue by picciama** [wilhelm-lab/oktoberfest#76]
**Describe the bug**

When trying to run the Oktoberfest Tutorial, with the standard Tritonserver instance via koina.proteomicsdb.org:443, I get the following error: 
`InferenceServerException: [StatusCode.UNAVAILABLE] failed to connect to all addresses; last error: INTERNAL: ipv4:131.159.152.5:443: Trying to connect an http1.x server`

**To Reproduce**
Run the tutorial notebook for e.g. spectral library generation

**Expected behavior**
The server should return predictions, using grpc.

**System [please complete the following information]:**

-   OS: debian 11
-   Language Version: Python 3.9
-   tritonclient: 2.34.0 with extra grpc

**Additional context**
Testing the feature/koina_grpc branch to merge it into development.
This problem was already observed by @mostafakalhor afaik.
@moomboh might have traced this to sth. related with two docker instances running on the same machine.

**Comment by LLautenbacher** [comment]
The networking/nginx side changed since I set up the Koina branch you will need to connect to the server like this `grpcclient.InferenceServerClient(url=server_url, ssl=True)`
