### ISSUE TITLE
Error when importing run_job from oktoberfest(in tutorial)

### ISSUE THREAD

**Issue by NormanRog** [wilhelm-lab/oktoberfest#85]
When I tried to execute the first cell of the tutorial jupyter notebook, 
I received the following error message:
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-1-aabb677243f8> in <module>
      1 import os
----> 2 from oktoberfest.runner import run_job
      3 import json
      4 import urllib.request
      5 import shutil

~/anaconda3/lib/python3.8/site-packages/oktoberfest/__init__.py in <module>
     15 import time
     16 
---> 17 from . import runner
     18 
     19 CONSOLE_LOG_LEVEL = logging.INFO

~/anaconda3/lib/python3.8/site-packages/oktoberfest/runner.py in <module>
     12 from .ce_calibration import CeCalibration, SpectralLibrary
     13 from .data.spectra import Spectra
---> 14 from .re_score import ReScore
     15 from .utils.config import Config
     16 from .utils.plotting import plot_all

~/anaconda3/lib/python3.8/site-packages/oktoberfest/re_score.py in <module>
      4 from typing import List, Optional, Union
      5 
----> 6 import mokapot
      7 import numpy as np
      8 import pandas as pd

~/anaconda3/lib/python3.8/site-packages/mokapot/__init__.py in <module>
     16         pass
     17 
---> 18 from .dataset import LinearPsmDataset
     19 from .model import Model, PercolatorModel, save_model, load_model
     20 from .brew import brew

~/anaconda3/lib/python3.8/site-packages/mokapot/dataset.py in <module>
     23 import pandas as pd
     24 
---> 25 from . import qvalues
     26 from . import utils
     27 from .parsers.fasta import read_fasta

~/anaconda3/lib/python3.8/site-packages/mokapot/qvalues.py in <module>
      4 import numpy as np
      5 import pandas as pd
----> 6 import numba as nb
      7 
      8 

~/anaconda3/lib/python3.8/site-packages/numba/__init__.py in <module>
     41 
     42 # Re-export vectorize decorators and the thread layer querying function
---> 43 from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
     44                             get_num_threads, set_num_threads)
     45 

~/anaconda3/lib/python3.8/site-packages/numba/np/ufunc/__init__.py in <module>
      1 # -*- coding: utf-8 -*-
      2 
----> 3 from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
      4 from numba.np.ufunc._internal import PyUFunc_None, PyUFunc_Zero, PyUFunc_One
      5 from numba.np.ufunc import _internal, array_exprs

~/anaconda3/lib/python3.8/site-packages/numba/np/ufunc/decorators.py in <module>
      1 import inspect
      2 
----> 3 from numba.np.ufunc import _internal
      4 from numba.np.ufunc.parallel import ParallelUFuncBuilder, ParallelGUFuncBuilder
      5 

SystemError: initialization of _internal failed without raising an exception

I installed oktoberfest, as recommended in the ReadMe, via pip and got no error message for that installation.
Thus I guess the reason for the error doesn't have to do with a wrong installation.

**Comment by picciama** [comment]
@NormanRog Please provide me with the versions of mokapot, numpy, numba, spectrum-fundamentals, spectrum-io, oktoberfest.
Please also veryify: Is this working in python 3.9?

Generally, numba is compiled to work for specific numpy versions. I suspect some incompatibility here.

**Comment by NormanRog** [comment]
@picciama Updated it to python 3.9, now I receive a different error message:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[4], line 2
      1 import os
----> 2 from oktoberfest.runner import run_job
      3 import json
      4 import urllib.request

File ~/anaconda3/envs/py39/lib/python3.9/site-packages/oktoberfest/__init__.py:17
     14 import sys
     15 import time
---> 17 from . import runner
     19 CONSOLE_LOG_LEVEL = logging.INFO
     20 logger = logging.getLogger(__name__)

File ~/anaconda3/envs/py39/lib/python3.9/site-packages/oktoberfest/runner.py:12
      9 from spectrum_io import Spectronaut
     10 from spectrum_io.spectral_library import MSP
---> 12 from .ce_calibration import CeCalibration, SpectralLibrary
     13 from .data.spectra import Spectra
     14 from .re_score import ReScore

File ~/anaconda3/envs/py39/lib/python3.9/site-packages/oktoberfest/ce_calibration.py:15
     13 from .data.spectra import FragmentType, Spectra
     14 from .spectral_library import SpectralLibrary
---> 15 from .utils.plotting import plot_mean_sa_ce, plot_violin_sa_ce
     17 logger = logging.getLogger(__name__)
     20 class CeCalibration(SpectralLibrary):

File ~/anaconda3/envs/py39/lib/python3.9/site-packages/oktoberfest/utils/plotting.py:4
      1 from pathlib import Path
      2 from typing import Union
----> 4 import matplotlib.pyplot as plt
      5 import numpy as np
      6 import pandas as pd

File ~/.local/lib/python3.9/site-packages/matplotlib/__init__.py:131
    127 from packaging.version import parse as parse_version
    129 # cbook must import matplotlib only within function
    130 # definitions, so it is safe to import from it here.
--> 131 from . import _api, _version, cbook, _docstring, rcsetup
    132 from matplotlib.cbook import sanitize_sequence
    133 from matplotlib._api import MatplotlibDeprecationWarning

File ~/.local/lib/python3.9/site-packages/matplotlib/rcsetup.py:27
     25 from matplotlib import _api, cbook
     26 from matplotlib.cbook import ls_mapper
---> 27 from matplotlib.colors import Colormap, is_color_like
     28 from matplotlib._fontconfig_pattern import parse_fontconfig_pattern
     29 from matplotlib._enums import JoinStyle, CapStyle

File ~/.local/lib/python3.9/site-packages/matplotlib/colors.py:51
     49 from numbers import Number
     50 import re
---> 51 from PIL import Image
     52 from PIL.PngImagePlugin import PngInfo
     54 import matplotlib as mpl

File ~/.local/lib/python3.9/site-packages/PIL/Image.py:59
     58 def __getattr__(name):
---> 59     if name == "PILLOW_VERSION":
     60         _raise_version_warning()
     61         return __version__

ImportError: cannot import name 'DeferredError' from 'PIL._util' (/home/norman/.local/lib/python3.9/site-packages/PIL/_util.py)

Any suggestions how I should proceed?

**Comment by picciama** [comment]
@NormanRog as discussed privately, I will close this as it was resolved by using a clean conda environment.
