### ISSUE TITLE
Koina SSL issue

### ISSUE THREAD

**Issue by LLautenbacher** [wilhelm-lab/oktoberfest#93]
The ssl flag [here](https://github.com/wilhelm-lab/oktoberfest/blob/afe55e3d59847128f0bf1415b6f4e55a35da6e02/oktoberfest/spectral_library.py#L168) should be a config option. Otherwise, people can't connect to private Koina instances.

**Comment by picciama** [comment]
I pushed this to #94  https://github.com/wilhelm-lab/oktoberfest/pull/94/commits/7aa26cde52d6bd5bf24966cce100faf6c4aa74b6. Please test by pulling the branch.
